version: "3.8"

services:
  mysql-server:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=my_db
    ports:
      - "3306:3306"
    networks:
        - eda-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s

  member-service:
    image: member-service
    ports:
      - "8081:8080"
    depends_on:
      mysql-server:
        condition: service_healthy
    environment:
      - DB_HOST=mysql-server
      - DB_PORT=3306
      - DB_DATABASE=my_db
      - DB_ROOT_ID=root
      - DB_ROOT_PW=1234
    networks:
      - eda-network

networks:
  eda-network:
    driver: bridge